[[redirects]]
  from = "/static/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["ejs", "sharp", "better-sqlite3", "nanoid", "pg"]

[functions."app"]
  included_files = ["views/**", "public/**", "ales logo.png"]

